### PR TITLE
value -> hashed_certificate_value

### PR DESCRIPTION
**Pull request by andresilva91**
## Motivation

As discussed in eng meeting, making these names a bit less generic

## Proposal

Rename things. Names turned out a bit longer, which I think was expected, but please lmk if you guys have better name suggestions :)

## Test Plan

CI

### CODE REVIEW

**Comment by andresilva91** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1965?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1965** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1965?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1964** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1964?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andresilva91 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ma2bd — CHANGES_REQUESTED** [review]
see previous PR

**Review by ma2bd — COMMENTED** [review]
Once the type is not ambiguous any more, do we really to update the function names?

**Comment by andresilva91** [comment]
IMHO yes we do, because `read_value` for example by itself is also too generic. @afck any thoughts?

**Comment by ma2bd** [comment]
> IMHO yes we do, because `read_value` for example by itself is also too generic. @afck any thoughts?

But it's `Storage::read_value`

**Comment by andresilva91** [comment]
> But it's `Storage::read_value`
To me that looks like we're reading a generic value from `Storage` (which could be confusing when soon there'll be also a `read_blob`), but maybe I'm missing something

**Review by ma2bd — APPROVED** [review]

**Pull request merged**
