### PR TITLE
Use the LTO for the release compilation

### PR DESCRIPTION
**Pull request by MathieuDutSik**
## Motivation

We want to achieve as much performance as possible. LTO is an opportunity for this.

## Proposal

The following changes are done:
* Use the LTO for the release compilation.
* Disable debug, though that is less important.

## Test Plan

(A) CI is used for correctness.

(B) For the benchmarking, we use the storage-service with 10 runs, the first one being discarded. Three kinds of variables are obtained:
* Prometheus histograms
* Prometheus fault / (fault + success) variables.
* The CI log entries.

Prometheus histogram:
* 3.20 ms(main), **1.94 ms**(lto): block execution latency
* 0.55706 ms(main), **0.52813 ms**(lto): bytecode decompression latency
* 0.13201 ms(main), **0.12184 ms**(lto): contract instantiation latency
* 0.01713 ms(main), **0.01407 ms**(lto): key value store view get latency
* 0.19724 ms(main), **0.17164 ms**(lto): key value store view hash latency
* 0.19557 ms(main), **0.16832 ms**(lto): key value store view multi get latency
* **0.06341 ms**(main), 0.07566 ms(lto): key value store view write batch latency
* 0.50985 ms(main), **0.44639 ms**(lto): load chain latency
* **1.23 ms**(main), 1.88 ms(lto): load contract latency
* 0.49750 ms(main), **0.43653 ms**(lto): load view latency
* 0.21635 ms(main), **0.18994 ms**(lto): map view hash runtime
* 1.17 ms(main), **0.57807 ms**(lto): message execution latency
* 0.92464 ms(main), **0.71020 ms**(lto): operation execution latency
* 0.50642 ms(main), **0.37880 ms**(lto): reentrant collection view hash runtime
* **0.00133 ms**(main), 0.00171 ms(lto): register view hash runtime
* 2.28 ms(main), **1.83 ms**(lto): server request latency
* 0.87147 ms(main), **0.75809 ms**(lto): server request latency per request type
* 0.16125 ms(main), **0.14055 ms**(lto): set view hash runtime
* 0.40903 ms(main), **0.27436 ms**(lto): state hash computation latency
* 0.00054 ms(main), **0.00048 ms**(lto): lru caching service store clear journal latency
* 0.00343 ms(main), **0.00219 ms**(lto): lru caching service store clone with root key latency
* 0.13995 ms(main), **0.12692 ms**(lto): lru caching service store connect latency
* **0.05483 ms**(main), 0.06215 ms(lto): lru caching service store contains key latency
* 0.23364 ms(main), **0.20520 ms**(lto): lru caching service store contains keys latency
* 0.20884 ms(main), **0.18448 ms**(lto): lru caching service store find key values by prefix latency
* 0.25197 ms(main), **0.23062 ms**(lto): lru caching service store find keys by prefix latency
* 0.21763 ms(main), **0.19785 ms**(lto): lru caching service store read multi value bytes latency
* 0.00822 ms(main), **0.00630 ms**(lto): lru caching service store read value bytes latency
* 0.28704 ms(main), **0.24519 ms**(lto): lru caching service store write batch latency
* 0.00006 ms(main), **0.00005 ms**(lto): service store clear journal latency
* 0.00121 ms(main), **0.00084 ms**(lto): service store clone with root key latency
* 0.05820 ms(main), **0.04667 ms**(lto): service store connect latency
* 0.23936 ms(main), **0.22195 ms**(lto): service store contains key latency
* 0.23126 ms(main), **0.20353 ms**(lto): service store contains keys latency
* 0.20718 ms(main), **0.18278 ms**(lto): service store find key values by prefix latency
* 0.25014 ms(main), **0.22901 ms**(lto): service store find keys by prefix latency
* 0.21490 ms(main), **0.19562 ms**(lto): service store read multi value bytes latency
* 0.21241 ms(main), **0.18761 ms**(lto): service store read value bytes latency
* 0.27406 ms(main), **0.23491 ms**(lto): service store write batch latency

Prometheus fault/(fault + success):
* 19.75 %(main), **18.60 %**(lto): num cache fault
* 54.65 %(main), **52.42 %**(lto): value cache miss

CI log:
* 44.80 ms(main), **36.19 ms**(lto): Closing chain confirmed
* 45.88 ms(main), **38.62 ms**(lto): Transfer confirmed
* 809.38 ms(main), **643.49 ms**(lto): Application published and created
* 90.72 ms(main), **75.17 ms**(lto): Application created
* 50.69 ms(main), **42.62 ms**(lto): Opening a new chain confirmed
* 8.85 ms(main), **6.94 ms**(lto): Chain linked to key
* 0.71456 ms(main), **0.04406 ms**(lto): Key generated
* 661.45 ms(main), **497.38 ms**(lto): Wallet initialized
* 1.98 ms(main), **1.21 ms**(lto): Local balance obtained
* 150.09 ms(main), **115.86 ms**(lto): Synchronized chain information
* 2.64 ms(main), **1.92 ms**(lto): Balance obtained
* 50.50 ms(main), **41.06 ms**(lto): Opening a new multi-owner chain confirmed
* 35.78 ms(main), **28.00 ms**(lto): Data blob published
* 44.06 ms(main), **34.78 ms**(lto): Data blob read
* 148.89 ms(main), **134.78 ms**(lto): Processed incoming messages
* 604.06 ms(main), **485.39 ms**(lto): Bytecode published
* 36.83 ms(main), **28.22 ms**(lto): Operation confirmed

## Release Plan

This is quite important for TestNet / DevNet as it changes nothing about the use and only requires a compilation for better performance.

## Links

The software used for the running is https://github.com/MathieuDutSik/linera_parsing_tools
The specific programs used are:
* run_and_obtain_metrics
* slack_benchmarks_formatting

### CODE REVIEW

**Review by deuszx — APPROVED** [review]
How does it affect the CI times? Do they get much longer?

**Review by afck — DISMISSED** [review]
> How does it affect the CI times? Do they get much longer?

At a glance it looks like it doesn't take longer at all! (I just compared a few of them to another PR.)

**Comment by ma2bd** [comment]
IIRC `debug` is about debug symbols which I would strongly suggest to keep. We don't really care about binary size here

**Comment by MathieuDutSik** [comment]
> [MathieuDutSik](/MathieuDutSik)

The impacted code by this decision are:
* The storage-service server but this compiles fast.
* The `check_copyright_header` (no idea why)
* The `long_faucet_chain_test`.

I did not do benchmark for the runtime of compiling, but as far as I can see there is not much difference between LTO and not LTO.

**Review by afck — APPROVED** [review]

**Comment by MathieuDutSik** [comment]
> IIRC `debug` is about debug symbols which I would strongly suggest to keep. We don't really care about binary size here

Unfortunately, the docker is no longer passing the CI when `debug=true`.

**Comment by ndr-ds** [comment]
Seems like the runner was killed for some reason? Doesn't look like an actual failure. If this had any effect on the `Docker` CI it would be maybe timing out, but it got killed after 20 something minutes even though the timeout is 40 minutes.
I started a rerun of it.

**Comment by MathieuDutSik** [comment]
> Seems like the runner was killed for some reason? Doesn't look like an actual failure. If this had any effect on the `Docker` CI it would be maybe timing out, but it got killed after 20 something minutes even though the timeout is 40 minutes. I started a rerun of it.

After changing to a beefier machine, that test passed in 25 minutes.

**Pull request merged**
