### PR TITLE
fix: use the `linera_base::sync::Lazy` instead of `once_cell::sync::Lazy`

### LINKED ISSUE #958: Use std instead of once_cell
After lazy_static and once_cell, there is now support for one-time initializers directly in the standard library:
https://doc.rust-lang.org/stable/std/sync/struct.OnceLock.html

This task is about migrating away from once_cell and using the standard library instead throughout the codebase.

### PR DESCRIPTION
**Pull request by duguorong009**
## Motivation

Use the `linera_base::sync::Lazy` instead of `once_cell::sync::Lazy`

## Proposal

Use the `linera_base::sync::Lazy` throughout the codebase

## Links

Closes #958

### CODE REVIEW

**Comment by ma2bd** [comment]
Hey @duguorong009, Thanks for the PR. Your code is very good but I realize now that the issue that I created (#958) was a bit silly: what we want is [`std::sync::LazyLock`](https://doc.rust-lang.org/std/sync/struct.LazyLock.html), which is not available on stable Rust, unfortunately.

Instead, can you try to migrate to `linera_base::sync::Lazy` on top of the commit inside this draft PR https://github.com/linera-io/linera-protocol/pull/1375 ?

**Comment by duguorong009** [comment]
Thanks for quick reply! @ma2bd 
I will migrate to `linera_base::sync::Lazy` after rebasing the commit.

**Comment by duguorong009** [comment]
@ma2bd 
I cannot cherry-pick the commit from your fork repo branch.
I will wait for it to be merged. And go for migration.

**Comment by ma2bd** [comment]
> @ma2bd I cannot cherry-pick the commit from your fork repo branch. I will wait for it to be merged. And go for migration.

@duguorong009 #1375 has landed

**Comment by duguorong009** [comment]
@ma2bd 
I finished the migration.
Pls go for review.

**Comment by ma2bd** [comment]
Thanks! It's looking good! Let's wait for the CI

**Review by ma2bd — APPROVED** [review]

**Comment by duguorong009** [comment]
@ma2bd 
Can I push one commit for lint error? 
I should remove the unused deps(`once_cell`) from other packages.

**Comment by afck** [comment]
It looks like you also need to update the `Cargo.lock` files in `examples`.
(The tests will only pass if all the `Cargo.lock` files are in sync with their corresponding `Cargo.toml`s.)

**Pull request merged**
