### PR TITLE
Log server request latency

### PR DESCRIPTION
**Pull request by andresilva91**
## Motivation

Logging some metrics from our list. Server latency will be an important one

## Proposal

Implementing server latency Histogram metric

## Test Plan

Ran validator locally, ran a benchmark against it, and saw metric properly logged:

### CODE REVIEW

**Comment by andresilva91** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1137** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1137" target="_blank">Graphite</a> 
    * **PR #1138** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1138" target="_blank">Graphite</a> 
      * **PR #1139** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1139" target="_blank">Graphite</a> 
        * **PR #1144** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1144" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1144?utm_source=stack-comment).

**Review by afck — APPROVED** [review]

**Review by afck — COMMENTED** [review]
I wonder if we should, in the future, measure latency for the different kinds of requests separately: Submitting a confirmed block certificate, proposing a new block, asking for a chain info, etc.

**Comment by andresilva91** [comment]
Yes, definitely. We should have more granular latency measurements, as well as maybe add labels to this one so we can filter out what kind of request this latency is for. Maybe both :)

**Comment by andresilva91** [comment]
### Merge activity

* **Oct 25, 11:42 AM**: @andresilva91 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1144).

**Pull request merged**
