### PR TITLE
Check if Cargo.toml is sorted on linter

### PR DESCRIPTION
**Pull request by andresilva91**
## Motivation

Follow up from previous PR, we need to enforce sorting

## Proposal

Add sorted check to linter

## Test Plan

CI

### CODE REVIEW

**Comment by andresilva91** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1112** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1112" target="_blank">Graphite</a> 
    * **PR #1113** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1113" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1113?utm_source=stack-comment).

**Comment by andresilva91** [comment]
After this succeeds, I'll stack it on top of main to make sure if fails properly too, then restack it here

**Review by christos-h — APPROVED** [review]
Nice!

**Review by ma2bd — APPROVED** [review]
shipit!

**Comment by andresilva91** [comment]
### Merge Activity

* **Oct 10, 8:58 PM**: @andresilva91 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1113).

**Pull request merged**
