### PR TITLE
Adding Prometheus/Grafana to Helm deployment

### PR DESCRIPTION
**Pull request by andresilva91**
## Motivation

We need to track our metrics

## Proposal

We'll be using Prometheus + Grafana to log and track our metrics

## Test Plan

Ran the script, port forwarded for grafana, managed to access the web dashboard

## Release Plan

- [x] All good!
- [ ] Need to bump the major/minor version number in the next release of the crates.
- [ ] Need to update the developer manual.
- [ ] This PR is adding or removing Cargo features.
- [ ] Release is blocked and/or tracked by other issues (see links above)

## Reviewer Checklist

- [ ] The title and the summary of the PR are short and descriptive.
- [ ] The proposed solution achieves the goals stated in the PR.
- [ ] The test plan is reproducible and provides sufficient coverage.
- [ ] The release plan is adequate.
- [ ] The commits correspond to distinct logical changes.
- [ ] The code follows the [coding guidelines](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md).
- [ ] The proposed changes look correct.
- [ ] The CI is passing.
- [ ] All of the above!

### CODE REVIEW

**Comment by christos-h** [comment]
Yeah I'm not sure about this, the diff is enormous. Let's discuss and see what other options we have.

**Comment by andresilva91** [comment]
Alright I'll switch back to remote `helm install` for now, then we can follow up with subcharts

**Comment by christos-h** [comment]
> Alright I'll switch back to remote helm install for now, then we can follow up with subcharts

Ok I'll merge this now to unblock you and I'll figure out our sub-charting strategy.

**Review by christos-h — APPROVED** [review]
LGTM

**Pull request merged**
