### PR TITLE
Sort all Cargo.toml files

### PR DESCRIPTION
**Pull request by andresilva91**
## Motivation

These should be kept sorted

## Proposal

Sorted them using `cargo sort -w`

## Test Plan

CI

### CODE REVIEW

**Comment by andresilva91** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1112** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1112" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1112?utm_source=stack-comment).

**Review by ma2bd — APPROVED** [review]
nice!

**Review by christos-h — APPROVED** [review]
LGTM!

**Comment by andresilva91** [comment]
### Merge Activity

* **Oct 10, 8:58 PM**: @andresilva91 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1112).

**Pull request merged**
