### PR TITLE
Fungible app support send token to applications

### PR DESCRIPTION
**Pull request by edwardluu**
## Motivation 
Update Fungible App support send token to applications
Issue from here:  https://github.com/linera-io/linera-protocol/issues/2549

## Proposal
- Update the display balance token of the Application 
- Add new options for **Account** or **Application**  in Make payment form.

## Test Plan
If the URL doesn't have an **Owner ID** the app will get an **App ID**  by default for the owner.
example for Application:  `http://localhost:3000/$CHAIN_1?app=$APP_ID&port=$PORT` 
Video for update: https://youtu.be/nqNuv0F6UgA

Screenshot 2024-10-08 at 17 25 13

### CODE REVIEW

**Comment by jvff** [comment]
This is great, thanks! I think one small change is still needed though. I like the idea of trying to get a default account for when the frontend loads, but using the application account won't work. The fungible token application can have a balance, but it has no way to transfer the funds in its own account, only the funds in user accounts and other applications (that have the code to request transfers).

I think we can remove the default for now, and we can work at obtaining a default user account later.

**Comment by edwardluu** [comment]
Hi @jvff, Thank you for the feedback. So now we do not need to show the application account balance and make an options for type account make a payment, right?

**Comment by edwardluu** [comment]
Hi @jvff  Update the app with the new commit
- Remove the default account balance

**Review by jvff — APPROVED** [review]
I'm really sorry for taking so long to answer. This looks great! Thank you very much for the changes :D

**Pull request merged**
