### PR TITLE
Adding option to net up --kubernetes to build within docker container

### PR DESCRIPTION
**Pull request by andresilva91**
## Motivation

Cross compiling is a pain in general

## Proposal

Adding option to just build within the container

## Test Plan

Ran passing binaries, still works.
Ran passing binaries and the new flag, fails as expected.
Ran passing the new flag, builds within container and starts cluster as expected.

### CODE REVIEW

**Comment by andresilva91** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1409** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1409?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1409?utm_source=stack-comment).

**Review by Twey — CHANGES_REQUESTED** [review]
Hey, thanks for this! It should make my life a lot easier while I'm working on the infra 😁

Just one thing I'm a bit less sure about — I'm generally not a fan of having arguments that allow nonsensical combinations (like `--container-build --binaries-dir`) even if we check for them.  Would it be possible instead to interpret a lack of `--binaries-dir` directly as building in the container? I think this should be the default anyway, as it's much more robust.

I think that would make the code simpler too :)

**Comment by andresilva91** [comment]
The only reason why I didn't do it like that was that we also have the case where someone installs the binaries using `cargo install linera-service`, and doesn't have anything compiled locally. Technically it should also work in this case (it will fetch the binary directory and pass that to the Dockerfile).
But I guess we could enforce that we want this to be used only with compiled binaries, since this will mostly be used by us (developers) anyways.

**Comment by Twey** [comment]
I think my ideal solution here would be:
- have one flag (probably `--binaries-dir` is no longer an appropriate name for it) that takes an optional argument to the binaries path
- if the flag is provided and the argument is provided, use the argument as a path to the binaries
- if the flag is provided, but the binaries path isn't, use `PATH` to try to find the binaries
- if the flag is not provided at all, build in the container

**Review by Twey — APPROVED** [review]
Steve Ballmer dancing at the Windows 95 launch party

**Pull request merged**
