### PR TITLE
Instrumenting code with Prometheus metrics

### PR DESCRIPTION
**Pull request by andresilva91**
## Motivation

Now that we have Prometheus support on our servers, let's add some metrics

## Proposal

Adding metrics from https://docs.google.com/spreadsheets/d/1tHo8iKzrlkuYeN2Yu7a6MfwQd-P2KNA9BlnhcASoEQY/edit?pli=1#gid=0

## Test Plan

Run locally, make sure metrics are there

### CODE REVIEW

**Comment by andresilva91** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1131** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1131" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1131?utm_source=stack-comment).

**Comment by christos-h** [comment]
You should be able to use [`OnceCell`](https://doc.rust-lang.org/nightly/std/cell/struct.OnceCell.html) in the standard library?

**Comment by andresilva91** [comment]
I thought so too, but it seems like `Lazy` is not yet stabilized in `std::sync::Lazy`, apparently. So my plan is to move to it once it is

**Comment by andresilva91** [comment]
I'm also closing this draft and putting each metric in it's own PR to help the review and make sure we all agree in the methodology, as Matt suggested

**Pull request closed without merging**
