### PR TITLE
Use std::process::Command instead on wrappers

### PR DESCRIPTION
**Pull request by andresilva91**
## Motivation

Depending on where we're running this (what runtime), using the tokio one can make these calls hang. So it's better to use `std::process::Command` directly instead

## Proposal

Use `std::process::Command`

## Test Plan

Run from e2e tests, make sure they don't hang

### CODE REVIEW

**Comment by andresilva91** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1314** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1314?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1315** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1315?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1316** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1316?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1316?utm_source=stack-comment).

**Comment by ma2bd** [comment]
What do you mean "hang"? We probably want to stick with the same type of `Command` for everything

**Comment by andresilva91** [comment]
Seems like it was related to stdout/stderr like you mentioned. This is only triggered from inside `drop`, so my current guess is that as the tokio runtime is shutting down, stdout/stderr never get flushed, so code trying to capture the output in any way will be waiting for a buffer flush that never happen.
Just spawning the process and waiting on it to finish (with no stdout/stderr interaction) doesn't hang.

**Comment by andresilva91** [comment]
Branch and PR name are not correct now, so will close this one and send an updated one

**Pull request closed without merging**
