### PR TITLE
nit: about empty log line when starting services

### PR DESCRIPTION
**Pull request by ma2bd**
## Motivation

nicer logs

## Proposal

Add the newline only where it's needed.

## Test Plan

```
cargo test -p linera-service
target/debug/linera --version
```

### CODE REVIEW

**Comment by Twey** [comment]
During your all-nighter you wrote the [following comment](https://github.com/linera-io/linera-protocol/commit/7b9aa0152d732db128f17a15d1a90695e361a8c4#diff-43b667085f94410b49b6251a0a69d0dce477cb33a3b4ed0a2e1ef784e02e9e18R68-R69):
```rust
// Starting with a new line is convenient for the clap annotation:
// `#[command(version = linera_base::VersionInfo::default_str())]`
```

When I moved the version string into this crate I preserved it because of that — but if you think it should go now I have no objections :)

**Comment by Twey** [comment]
If `default_str` is now formatted specifically for `clap`, maybe we should rename it to something else that makes that association clear?

**Review by Twey — APPROVED** [review]
Approving this because it's only an internal API so I don't think it matters hugely, but with a suggestion.

**Comment by ma2bd** [comment]
> If `default_str` is now formatted specifically for `clap`, maybe we should rename it to something else that makes that association clear?

Maybe `default_clap_str` then ?

**Pull request merged**
